### PR TITLE
Menuroles

### PR DESCRIPTION
**Pull request by rjester**
#5 : Removed CustomRoleProvider since LocalDB is no longer used.
Only show Route Shape Upload, Bulk Stop Upload, and Role Manager if the authenticated user is in the Administrators role.

### CODE REVIEW

**Comment by rjester** [comment]
I only tested with an existing database.  I will try to reproduce the error and fix it.

**Comment by rjester** [comment]
I updated the pull request to only change the login partial view.  There is one possible issue related to creating the role data when the first user logs in and hiding the menu items that require an authorized user.  There aren't any visible links to click on to initiate the seeding of the data.  I could move that to a seed method that would be called when the database is created.

**Comment by rjester** [comment]
Are you still having problems editing a trolley with the latest pr?  I'm not getting any errors.

**Comment by bikeoid** [comment]
It works for me now - I am still fumbling with how to work Github!

**Pull request merged**
